export const REQUEST_BOOKS = 'REQUEST_BOOKS'
export const RECEIVE_BOOKS = 'RECEIVE_BOOKS'
export const REQUEST_CREATE_BOOK = 'REQUEST_CREATE_BOOK'
export const RECEIVE_CREATED_BOOK = 'RECEIVE_CREATED_BOOK'